quiet: False
keeptree: True
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: mocks
packages:
  github.com/vektra/mockery/v2/pkg:
    interfaces:
      TypesPackage:
  github.com/vektra/mockery/v2/pkg/fixtures:
    config:
      all: True
    interfaces:
      RequesterArgSameAsNamedImport:
      RequesterVariadic:
        config:
          with-expecter: False
        configs:
          - mockname: RequesterVariadicOneArgument
            unroll-variadic: False
          - mockname: RequesterVariadic
            unroll-variadic: True
      Expecter:
        config:
          with-expecter: True
        configs:
          - mockname: ExpecterAndRolledVariadic
            unroll-variadic: False
          - mockname: Expecter
            unroll-variadic: True
      RequesterReturnElided:
  github.com/vektra/mockery/v2/pkg/fixtures/recursive_generation:
    config:
      recursive: True
      all: True
      dir: "{{.InterfaceDir}}"
      filename: "{{.InterfaceName}}_mock.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: True